#!/bin/bash

function keygen(){
    DIR="$HOME/.ssh"
    KEYS="$DIR/keys"
    AUTH="$DIR/authorized_keys"
    KEY="$1"
    mkdir -p "$KEYS"

    if [ -f "$KEYS/$KEY" ]; then
        echo "KEY '$KEY' already exists in '$KEYS/'" 1>&2
    else
        COMMENT="$KEY $(date '+%Y-%m-%d %H:%M:%S')"
        ssh-keygen -q -t rsa -b 4096 -N '' -f "$KEYS/$KEY" -C "$COMMENT"
        chmod 600 "$KEYS/$KEY"
        echo -e "Key '$KEY' created in '$KEYS/'...\n"

        while [ 1 ]; do
            read -p "Add to authorized keys (Y/n)? " -n 1 -r INPUT 2>&1; echo
            case "$INPUT" in
                y|Y|'' )
                    cat "$KEYS/${KEY}.pub" >> "$AUTH"
                    break;
                    ;;
                n|N ) break;;
            esac
        done
    fi
}

if [ $# -eq 1 ]; then
    keygen $1
else
    echo "Usage: $(basename $0) <key name>"
fi

