#!/bin/bash

source environment

mkdir -p ${BACKUPDIR}

for DIR in $DIRS; do
    for FILE in $(find $DIR -xtype f); do
        TARGETFILE="${TARGET}/${FILE#*/}"
        if [[ -L "$TARGETFILE" ]]; then
            SYMLINK=$(readlink -f "$TARGETFILE")
            if [[ "$SYMLINK" == *"$SCRIPTDIR"* ]]; then
                continue
            fi
        fi

        if [ -f "${TARGETFILE}" ]; then
            echo "BACKUP ${TARGETFILE}"
            if [[ -L "${TARGETFILE}" ]]; then
                echo "${TARGETFILE} is a link"
            fi
            rsync --links --relative "${TARGETFILE}" "${BACKUPDIR}"
            rm "${TARGETFILE}"
        fi
    done
done

